language: android
jdk: oraclejdk7

env:
   global:
    # Initiating clean Gradle output
        - TERM=dumb
    # Amount of memory granted to Gradle JVM
        - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"

android:
  components:
       - tools
       - build-tools-23.0.2
       - android-23
       - extra-android-support
       - extra-google-google_play_services
       - extra-google-m2repository
       - extra-android-m2repository

before_install:
     - chmod +x gradlew

script:
    - echo "Travis branch is $TRAVIS_BRANCH"
    - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
    - ./gradlew assemble
